export const LOGIN = "/login";
export const SIGN_UP = "/sign-up";
export const LOST_PASS = "/lost-password";
export const EVENT = (eventId) => `/event/${eventId}`;
export const EVENT_ADD = "/add/event";
export const EVENT_EDIT = (eventId) => `/edit/event/${eventId}`;
export const MY_TEAMS = "/teams/me";
export const MY_EVENTS = "/events/me";
export const MY_ACCOUNT = "/me";
export const EDIT_ACCOUNT = "/edit/me";
export const USER = (userId) => `/user/${userId}`;
export const TEAM = (teamId) => `/team/${teamId}`;
export const TEAM_ADD = "/add/team";
export const TEAM_EDIT = (teamId) => `/edit/team/${teamId}`;
export const ABOUT = "/about";
export const SEARCH = "/search";
export const HOME = "/";
